### ISSUE TITLE
[BUG] Created catalog disappears at times

### ISSUE THREAD

**Issue by jey-exp** [realChakrawarti/yt-catalog#85]
I created a catalog few days back. Now when I tried to view it, it is not displayed in the catalog section, but when i try to load the particular url of that catalog, it works. (Attached video - reproducing the bug)

It loaded first, but on a re-load it disappeared.

[Video of the bug](https://www.loom.com/share/f3fc34c1f1034b4e8941365006143ea7?sid=9d603cfb-18f3-44ab-98f4-f9692b99c64c)

**Comment by realChakrawarti** [comment]
Thanks for reporting the issue. 

The expected behavior is when you create a catalog and update the same with some channels, the `/explore/catalogs` page should revalidate (mark the cache on vercel for this page stale) and show your created catalog on the next page load, which doesn't seem to be happening here.

I bet that `/explore` page (w/ tabs navigation) is functioning as expected!?

This might be because of not revalidating the path of recently added catalogs page `/explore/catalogs` and defaulting to the old `/explore` page.

The same thing might be happening for archive page `/explore/archives` as well.

### Potential changes for fixing this issue

#### On catalog update:

- [ ] Update L70 from `revalidatePath("/explore");` to `revalidatePath("/explore/catalogs");`

https://github.com/realChakrawarti/yt-catalog/blob/cc02994d6ecdaf42b69e91579cdff06b18cd5e6a/src/app/api/catalogs/%5BcatalogId%5D/update/route.ts#L47-L74 

#### On archive update:

- [ ] Add the same logic for archive on L20, `revalidatePath("/explore/archives");`

https://github.com/realChakrawarti/yt-catalog/blob/cc02994d6ecdaf42b69e91579cdff06b18cd5e6a/src/app/api/archives/%5BarchiveId%5D/update/route.ts#L14-L22


@jey-exp If you want to pick this up and fix, please feel free to make the above changes and raise a PR or I could do the same by today EOD.

Again, thanks for reporting this 😊

**Comment by jey-exp** [comment]
Thanks for acknowledging it.

>I bet that /explore page (w/ tabs navigation) is functioning as expected!?
The catalog doesn't appear here also,  I am not sure if I am doing things wrong. I logged out and logged in again, only then I am facing these issues. 

Also I have observed an interesting behaviour. Even when I am not logged in, the catalog page is accessible. Is that an expected behaviour. 

![image](https://github.com/user-attachments/assets/d0329bcd-74a9-4774-a660-0d3600074738)

**Comment by realChakrawarti** [comment]
@jey-exp Thanks for reaching out! 😊

> The catalog doesn't appear here also, I am not sure if I am doing things wrong. I logged out and logged in again, only then I am facing these issues.

I will take a look at it. Correct me and if possible please share when the catalog doesn't appear on these below steps:
1. Login/signup 
2. Create a catalog then add some channels, apply those changes
3. Visit `/explore` or `/explore/catalogs`, **[Your created catalog is visible?]**
4. Log out, visit `/explore` or `/explore/catalogs`, **[Your created catalog is visible?]**
5. Log in, visit `/explore` or `/explore/catalogs`, **[Your created catalog is visible?]**

> Also I have observed an interesting behaviour. Even when I am not logged in, the catalog page is accessible. Is that an expected behaviour.

Yes, this is expected behavior. The catalogs created are public in nature, that means you can watch videos of the catalog without ever logging in or even signing up once created. You can share your catalog with others and they can watch videos from those channels as catalog feed get updated every 4 hours.

The same is applicable for archives as well. 

What shouldn't be accessible once logged out is dashboard `/dashboard` and the creation part of either catalogs or archives.
